ConsoleCalc/ItUniver.Calc.WebCalc/Controllers/CalcController.cs
using ConsoleCalc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebCalc.Models;
using System.Diagnostics;
using System.Threading;

namespace WebCalc.Controllers
{
    [Authorize]
    public class CalcController : Controller
    {
        // GET: Calc
        public ActionResult Index()
        {
            var model = new OperationModel();

            var operations = new List<SelectListItem>();
            operations.AddRange(
                DbHelper.GetAllOperationItems()
                .Select(o => new SelectListItem
                {
                    Text = o.Name,
                    Value = o.Name
                })
                );

            model.AllOperations = operations;

            return View(model);
        }

        [HttpPost]
        public ActionResult Index(OperationModel model)
        {
            var calc = new Calculator();

            Stopwatch stopWatch = new Stopwatch();
            stopWatch.Start();

            model.Result = calc.Exec(model.Operation, model.Args.ToArray());

            stopWatch.Stop();
            var speed = stopWatch.ElapsedMilliseconds;

            // TODO: закжшировать список операций
            // TODO: сохранять последнюю операцию
            var operations = new List<SelectListItem>();
            operations.AddRange(
                DbHelper.GetAllOperationItems()
                .Select(o => new SelectListItem
                {
                    Text = o.Name,
                    Value = o.Name
                })
                .Reverse()
                );

            model.AllOperations = operations;

            if (model.Operation != null && model.Args != null)
                DbHelper.AddToHistory(model.Operation, User.Identity.Name, model.Args.ToArray(), (double)model.Result, speed);

            return View(model);
        }
    }
}

ConsoleCalc/ItUniver.Calc.WebCalc/Controllers/HistoryController.cs
using ItUniver.Calc.DB.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebCalc.Controllers
{
    [Authorize]
    public class HistoryController : Controller
    {
        // GET: History
        public ActionResult Index()
        {
            var history = DbHelper.Users.GetByLogin(User.Identity.Name).History;

            return View(history);
        }
    }
}

ConsoleCalc/ItUniver.Calc.WebCalc/Controllers/OperationController.cs
using ItUniver.Calc.DB.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebCalc.Controllers
{
    [Authorize]
    public class OperationController : Controller
    {
        // GET: Operation
        public ActionResult Index()
        {
            var operations = new List<OperationItem>()
            {
                new OperationItem() { Id = 1, ArgsCount = 2, Name = "sum", Owner = "ituniver", CreationDate = DateTime.Now },
                new OperationItem() { Id = 1, ArgsCount = 2, Name = "sub", Owner = "ituniver", CreationDate = DateTime.Now },
                new OperationItem() { Id = 1, ArgsCount = 2, Name = "div", Owner = "ituniver", CreationDate = DateTime.Now },
                new OperationItem() { Id = 1, ArgsCount = 2, Name = "pow", Owner = "ituniver", CreationDate = DateTime.Now },
                new OperationItem() { Id = 1, ArgsCount = 2, Name = "credit", Owner = "ituniver", CreationDate = DateTime.Now },
            };

            return View(operations);
        }
    }
}

ConsoleCalc/ItUniver.Calc.WebCalc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Калькулятор</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body style="
    font-family: 'courier new';
    font-size: 18px;
    color: #ffffff;
    background: #2d416f;">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Вычислитель", "Index", "Calc", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("История", "Index", "History")</li>
                    <li>@Html.ActionLink("Операции", "Index", "Operation")</li>

                    @if (User.Identity.IsAuthenticated)
                    {
                        @User.Identity.Name;
                        <li>@Html.ActionLink("Выйти", "Logout", "Account")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Зарегистрироваться", "Registration", "Account")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ITUniver Company</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>